### ISSUE TITLE
Gratulacje:)

### ISSUE THREAD

**Issue by astratow** [MaciejWiatr/wiatr-blog#1]
witam
Bardzo fajny projekt, cho¢ nie wiem czy te ciemne kolory są uniwersalne. Email można zrobić klikalny albo jeszcze lepiej formularz kontaktowy.  Sekcja kontakt i zachęta do zapisania się na listę w jednym bloku to chyba nie najlepszy pomysł... Na telefonie ok, ale na laptopie wygląda asymetrycznie.
Mam nadzieję, że moje uwagi pomogą. Pozdrawiam szanownego rannego ptaszka!
Artur

**Comment by MaciejWiatr** [comment]
dzięki
